export const CREATE_MOMO_PAYMENT_REQUEST = "CREATE_MOMO_PAYMENT"
export const CREATE_MOMO_PAYMENT_SUCCESS = " CREATE_MOMO_PAYMENT_SUCCESS"
export const CREATE_MOMO_PAYMENT_FAIL = "CREATE_MOMO_PAYMENT_FAIL"
export const CREATE_MOMO_PAYMENT_RESET = "CREATE_MOMO_PATMENT_RESET"

